management.tcp.port = $(RABBITMQ_MANAGEMENT_PORT)
management.tcp.ip = $(RABBITMQ_MANAGEMENT_IP)

load_definitions = $(RABBITMQ_DEFINITIONS_FILE)

log.console = true
log.console.level = $(RABBITMQ_LOG_LEVEL)

vm_memory_high_watermark.relative = $(RABBITMQ_VM_MEMORY_HIGH_WATERMARK)
disk_free_limit.absolute = $(RABBITMQ_DISK_FREE_LIMIT)